# Generated by Django 3.1.5 on 2021-01-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liscense_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('CR', 'Car'), ('VN', 'Van'), ('BS', 'Bus'), ('TK', 'Truck')], max_length=2, null=True),
        ),
    ]
