# Generated by Django 3.1.5 on 2021-01-31 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0002_auto_20210131_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ride_owner_uid', to='didi.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserOwnRide',
        ),
    ]
