# Generated by Django 3.1.5 on 2021-01-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0003_auto_20210131_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='rider_id',
            new_name='ride_id',
        ),
    ]
