# Generated by Django 3.1.5 on 2021-02-05 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('didi', '0004_auto_20210131_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('vehicle_type', models.CharField(blank=True, choices=[('CR', 'Car'), ('VN', 'Van'), ('BS', 'Bus'), ('TK', 'Truck')], max_length=2, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('liscense_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_capacity', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='ride_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_owner_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialvehicleinfo',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdriveride',
            name='user_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usershareride',
            name='user_sharer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharer_uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
