# Generated by Django 3.1.5 on 2021-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0006_auto_20210206_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_number',
            field=models.CharField(blank=True, default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('CR', 'Car'), ('VN', 'Van'), ('BS', 'Bus'), ('TK', 'Truck')], default='CR', max_length=2),
            preserve_default=False,
        ),
    ]
