# Generated by Django 3.1.5 on 2021-02-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0007_auto_20210206_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialvehicleinfo',
            name='vehicle_owner',
        ),
        migrations.AddField(
            model_name='specialvehicleinfo',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_info_vehicle', to='didi.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialvehicleinfo',
            name='vehicle_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_info_info', to='didi.specialinfo'),
        ),
    ]
