# Generated by Django 3.1.5 on 2021-02-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0008_auto_20210206_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialvehicleinfo',
            name='vehicle_info',
        ),
        migrations.AddField(
            model_name='specialvehicleinfo',
            name='info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SVI_info', to='didi.specialinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialvehicleinfo',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SVI_vehicle', to='didi.vehicle'),
        ),
    ]
