# Generated by Django 3.1.5 on 2021-02-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0009_auto_20210206_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialinfo',
            name='info_id',
        ),
        migrations.AddField(
            model_name='specialinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
