# Generated by Django 3.1.5 on 2021-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0010_auto_20210206_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='ride_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
