# Generated by Django 3.1.5 on 2021-02-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0012_auto_20210206_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='request',
            field=models.ManyToManyField(to='didi.SpecialInfo'),
        ),
    ]
