# Generated by Django 3.1.5 on 2021-02-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0013_ride_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialvehicleinfo',
            name='info',
        ),
        migrations.RemoveField(
            model_name='specialvehicleinfo',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='feature',
            field=models.ManyToManyField(to='didi.SpecialInfo'),
        ),
        migrations.DeleteModel(
            name='RideSpecialRequest',
        ),
        migrations.DeleteModel(
            name='SpecialVehicleInfo',
        ),
    ]
