# Generated by Django 3.1.5 on 2021-02-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0015_auto_20210207_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdriveride',
            name='user_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle', to='didi.vehicle'),
        ),
    ]
