# Generated by Django 3.1.5 on 2021-02-12 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0016_auto_20210207_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 22, 59, 44, 184241)),
            preserve_default=False,
        ),
    ]
