# Generated by Django 3.1.5 on 2021-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0018_ride_start_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='start_time',
        ),
        migrations.AddField(
            model_name='usershareride',
            name='owner_psger_num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
