# Generated by Django 3.1.5 on 2021-02-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('didi', '0019_auto_20210213_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdriveride',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rid', to='didi.ride'),
        ),
        migrations.AlterUniqueTogether(
            name='usershareride',
            unique_together={('user_sharer', 'ride')},
        ),
    ]
