# Generated by Django 3.1.5 on 2021-02-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didi', '0020_auto_20210215_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershareride',
            old_name='owner_psger_num',
            new_name='psger_num',
        ),
    ]
